import type { PCMMandatoryType } from '@/lib/types'

export interface PCMFieldRule {
  field: string
  definition: string
  fillingRule: string
  roles: string[]
  httpCodes: string[]
  mandatory: PCMMandatoryType
  domain?: string
  maxSize?: string
  pattern?: string
  example?: string
}

export const BASE_PCM_FIELDS: PCMFieldRule[] = [
  {
    field: 'clientOrgId',
    definition: 'Identificador da organização cliente (iniciadora)',
    fillingRule: 'UUID da organização cliente no diretório de participantes',
    roles: ['CLIENT'],
    httpCodes: ['200', '201', '204', '400', '401', '403', '404', '422', '429', '500', '503', '504'],
    mandatory: 'client',
    pattern: '^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$',
    example: '1dbfe32a-5f1e-4841-a30c-9f1b5f24ad36',
  },
  {
    field: 'serverOrgId',
    definition: 'Identificador da organização servidora (detentora)',
    fillingRule: 'UUID da organização servidora no diretório de participantes',
    roles: ['SERVER'],
    httpCodes: ['200', '201', '204', '400', '401', '403', '404', '422', '429', '500', '503', '504'],
    mandatory: 'server',
    pattern: '^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$',
    example: '18a5f8fd-836e-4a7f-8db3-32d0c98da989',
  },
  {
    field: 'endpoint',
    definition: 'Endpoint da API chamada',
    fillingRule: 'Path completo do endpoint conforme especificação OpenAPI',
    roles: ['CLIENT', 'SERVER'],
    httpCodes: ['200', '201', '204', '400', '401', '403', '404', '422', '429', '500', '503', '504'],
    mandatory: 'both',
    example: '/open-banking/accounts/v2/accounts/{accountId}/balances',
  },
  {
    field: 'httpMethod',
    definition: 'Método HTTP utilizado na chamada',
    fillingRule: 'Método HTTP da requisição (GET, POST, PUT, PATCH, DELETE)',
    roles: ['CLIENT', 'SERVER'],
    httpCodes: ['200', '201', '204', '400', '401', '403', '404', '422', '429', '500', '503', '504'],
    mandatory: 'both',
    domain: 'GET, POST, PUT, PATCH, DELETE',
    example: 'GET',
  },
  {
    field: 'statusCode',
    definition: 'Código de status HTTP da resposta',
    fillingRule: 'Código HTTP retornado na resposta',
    roles: ['CLIENT', 'SERVER'],
    httpCodes: ['200', '201', '204', '400', '401', '403', '404', '422', '429', '500', '503', '504'],
    mandatory: 'both',
    example: '200',
  },
  {
    field: 'timestamp',
    definition: 'Data e hora da chamada',
    fillingRule: 'Timestamp no formato ISO 8601 com timezone UTC',
    roles: ['CLIENT', 'SERVER'],
    httpCodes: ['200', '201', '204', '400', '401', '403', '404', '422', '429', '500', '503', '504'],
    mandatory: 'both',
    pattern: '^\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2}(\\.\\d+)?Z$',
    example: '2026-01-20T10:30:00.000Z',
  },
  {
    field: 'fapiInteractionId',
    definition: 'Identificador de interação FAPI',
    fillingRule: 'UUID gerado conforme padrão FAPI para rastreabilidade da interação',
    roles: ['CLIENT', 'SERVER'],
    httpCodes: ['200', '201', '204', '400', '401', '403', '404', '422', '429', '500', '503', '504'],
    mandatory: 'both',
    pattern: '^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$',
    example: 'a1b2c3d4-e5f6-7890-abcd-ef1234567890',
  },
  {
    field: 'processTimespan',
    definition: 'Tempo de processamento da requisição em milissegundos',
    fillingRule: 'Tempo total de processamento da requisição, medido no servidor, em milissegundos',
    roles: ['SERVER'],
    httpCodes: ['200', '201', '204', '400', '401', '403', '404', '422', '429', '500', '503', '504'],
    mandatory: 'server',
    example: '150',
  },
  {
    field: 'clientSSId',
    definition: 'Identificador do Software Statement do cliente',
    fillingRule: 'Software Statement ID do aplicativo cliente registrado no diretório',
    roles: ['CLIENT'],
    httpCodes: ['200', '201', '204', '400', '401', '403', '404', '422', '429', '500', '503', '504'],
    mandatory: 'client',
    example: 'abc123def456',
  },
  {
    field: 'serverASId',
    definition: 'Identificador do Authorization Server do servidor',
    fillingRule: 'Authorization Server ID do servidor conforme diretório de participantes',
    roles: ['SERVER'],
    httpCodes: ['200', '201', '204', '400', '401', '403', '404', '422', '429', '500', '503', '504'],
    mandatory: 'server',
    example: 'as-server-001',
  },
  {
    field: 'endpointUriPrefix',
    definition: 'Prefixo da URI do endpoint',
    fillingRule: 'Base URL do endpoint da API, sem o path específico',
    roles: ['SERVER'],
    httpCodes: ['200', '201', '204', '400', '401', '403', '404', '422', '429', '500', '503', '504'],
    mandatory: 'server',
    example: 'https://api.banco.com.br/open-banking',
  },
  {
    field: 'correlationId',
    definition: 'Identificador de correlação entre chamadas',
    fillingRule: 'UUID para correlacionar chamadas entre cliente e servidor na mesma interação',
    roles: ['CLIENT', 'SERVER'],
    httpCodes: ['200', '201', '204', '400', '401', '403', '404', '422', '429', '500', '503', '504'],
    mandatory: 'both',
    pattern: '^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$',
    example: 'f47ac10b-58cc-4372-a567-0e02b2c3d479',
  },
  {
    field: 'clientOrgName',
    definition: 'Nome da organização cliente',
    fillingRule: 'Nome registrado da organização cliente no diretório',
    roles: ['CLIENT'],
    httpCodes: ['200', '201', '204', '400', '401', '403', '404', '422', '429', '500', '503', '504'],
    mandatory: 'client',
    example: 'BANCO EXEMPLO S.A.',
  },
  {
    field: 'serverOrgName',
    definition: 'Nome da organização servidora',
    fillingRule: 'Nome registrado da organização servidora no diretório',
    roles: ['SERVER'],
    httpCodes: ['200', '201', '204', '400', '401', '403', '404', '422', '429', '500', '503', '504'],
    mandatory: 'server',
    example: 'INSTITUICAO FINANCEIRA S.A.',
  },
  {
    field: 'additionalInfo.consentId',
    definition: 'Identificador do consentimento',
    fillingRule: 'ID do consentimento vinculado à chamada, no formato urn:bancoex:C1DD33123',
    roles: ['CLIENT', 'SERVER'],
    httpCodes: ['200', '201', '204', '400', '401', '403', '404', '422', '429', '500', '503', '504'],
    mandatory: 'both',
    example: 'urn:bancoex:C1DD33123',
  },
  {
    field: 'additionalInfo.tokenId',
    definition: 'Identificador do token de acesso',
    fillingRule: 'Hash do access token utilizado na chamada (SHA-256)',
    roles: ['CLIENT', 'SERVER'],
    httpCodes: ['200', '201', '204', '400', '401', '403', '404', '422', '429', '500', '503', '504'],
    mandatory: 'both',
    example: 'a3f2b7c9e1d4...',
  },
  {
    field: 'apiFamily',
    definition: 'Família da API',
    fillingRule: 'Identificador da família de API conforme catálogo do Open Finance',
    roles: ['CLIENT', 'SERVER'],
    httpCodes: ['200', '201', '204', '400', '401', '403', '404', '422', '429', '500', '503', '504'],
    mandatory: 'both',
    example: 'accounts',
  },
  {
    field: 'apiVersion',
    definition: 'Versão da API',
    fillingRule: 'Versão da API no formato vN (ex: v2)',
    roles: ['CLIENT', 'SERVER'],
    httpCodes: ['200', '201', '204', '400', '401', '403', '404', '422', '429', '500', '503', '504'],
    mandatory: 'both',
    pattern: '^v\\d+$',
    example: 'v2',
  },
]

export interface APIFamilyRules {
  family: string
  keywords: string[]
  pathPatterns: string[]
  additionalFields: PCMFieldRule[]
}

export const API_FAMILY_RULES: APIFamilyRules[] = [
  {
    family: 'consents',
    keywords: ['consentimento', 'consents', 'consent'],
    pathPatterns: ['/consents'],
    additionalFields: [
      {
        field: 'additionalInfo.dropReason',
        definition: 'Motivo do descarte do consentimento',
        fillingRule: 'Código do motivo de descarte quando o consentimento é descartado',
        roles: ['SERVER'],
        httpCodes: ['200', '201', '204'],
        mandatory: 'server',
        example: 'CUSTOMER_MANUALLY_REVOKED',
      },
      {
        field: 'additionalInfo.personType',
        definition: 'Tipo de pessoa (PF ou PJ)',
        fillingRule: 'Indica se o consentimento é de Pessoa Física (NATURAL) ou Jurídica (LEGAL)',
        roles: ['SERVER'],
        httpCodes: ['200', '201'],
        mandatory: 'server',
        domain: 'NATURAL, LEGAL',
        example: 'NATURAL',
      },
      {
        field: 'additionalInfo.status',
        definition: 'Status do consentimento',
        fillingRule: 'Status atual do consentimento conforme ciclo de vida',
        roles: ['CLIENT', 'SERVER'],
        httpCodes: ['200', '201'],
        mandatory: 'both',
        domain: 'AUTHORISED, AWAITING_AUTHORISATION, REJECTED, CONSUMED, REVOKED',
        example: 'AUTHORISED',
      },
      {
        field: 'additionalInfo.companyProfileInfo',
        definition: 'Informações do perfil da empresa',
        fillingRule: 'Dados adicionais do perfil corporativo quando aplicável',
        roles: ['SERVER'],
        httpCodes: ['200', '201'],
        mandatory: 'server',
        example: 'COMPANY_PROFILE_1',
      },
      {
        field: 'additionalInfo.journeyIsLinked',
        definition: 'Indica se a jornada está vinculada',
        fillingRule: 'Boolean indicando se a jornada de consentimento está vinculada a outra jornada',
        roles: ['SERVER'],
        httpCodes: ['200', '201'],
        mandatory: 'server',
        domain: 'true, false',
        example: 'false',
      },
      {
        field: 'additionalInfo.journeyLinkId',
        definition: 'Identificador de vinculação da jornada',
        fillingRule: 'ID de vínculo quando journeyIsLinked é true',
        roles: ['SERVER'],
        httpCodes: ['200', '201'],
        mandatory: 'server',
        example: 'link-abc-123',
      },
    ],
  },
  {
    family: 'accounts',
    keywords: ['contas', 'accounts', 'conta'],
    pathPatterns: ['/accounts'],
    additionalFields: [],
  },
  {
    family: 'credit-cards-accounts',
    keywords: ['cartão de crédito', 'credit-cards', 'credit cards', 'cartao de credito'],
    pathPatterns: ['/credit-cards-accounts'],
    additionalFields: [],
  },
  {
    family: 'customers',
    keywords: ['dados cadastrais', 'customers', 'cadastrais', 'personal', 'business'],
    pathPatterns: ['/customers'],
    additionalFields: [],
  },
  {
    family: 'loans',
    keywords: ['empréstimos', 'loans', 'emprestimos'],
    pathPatterns: ['/loans'],
    additionalFields: [],
  },
  {
    family: 'financings',
    keywords: ['financiamento', 'financings', 'financing'],
    pathPatterns: ['/financings'],
    additionalFields: [],
  },
  {
    family: 'invoice-financings',
    keywords: ['direitos creditórios', 'invoice-financings', 'direitos creditorios', 'desconto'],
    pathPatterns: ['/invoice-financings'],
    additionalFields: [],
  },
  {
    family: 'unarranged-accounts-overdraft',
    keywords: ['adiantamento', 'unarranged-accounts-overdraft', 'depositantes'],
    pathPatterns: ['/unarranged-accounts-overdraft'],
    additionalFields: [],
  },
  {
    family: 'funds',
    keywords: ['fundos de investimento', 'funds', 'fundos'],
    pathPatterns: ['/funds'],
    additionalFields: [],
  },
  {
    family: 'bank-fixed-incomes',
    keywords: ['renda fixa bancária', 'bank-fixed-incomes', 'renda fixa bancaria'],
    pathPatterns: ['/bank-fixed-incomes'],
    additionalFields: [],
  },
  {
    family: 'credit-fixed-incomes',
    keywords: ['renda fixa crédito', 'credit-fixed-incomes', 'renda fixa credito'],
    pathPatterns: ['/credit-fixed-incomes'],
    additionalFields: [],
  },
  {
    family: 'variable-incomes',
    keywords: ['renda variável', 'variable-incomes', 'renda variavel'],
    pathPatterns: ['/variable-incomes'],
    additionalFields: [],
  },
  {
    family: 'treasure-titles',
    keywords: ['títulos do tesouro', 'treasure-titles', 'tesouro direto', 'titulos do tesouro'],
    pathPatterns: ['/treasure-titles'],
    additionalFields: [],
  },
  {
    family: 'exchanges',
    keywords: ['câmbio', 'exchanges', 'cambio'],
    pathPatterns: ['/exchanges'],
    additionalFields: [],
  },
  {
    family: 'resources',
    keywords: ['recursos', 'resources'],
    pathPatterns: ['/resources'],
    additionalFields: [
      {
        field: 'additionalInfo.statusSummary.available',
        definition: 'Quantidade de recursos disponíveis',
        fillingRule: 'Número de recursos com status available retornados pela API',
        roles: ['SERVER'],
        httpCodes: ['200'],
        mandatory: 'server',
        example: '5',
      },
      {
        field: 'additionalInfo.statusSummary.unavailable',
        definition: 'Quantidade de recursos indisponíveis',
        fillingRule: 'Número de recursos com status unavailable retornados pela API',
        roles: ['SERVER'],
        httpCodes: ['200'],
        mandatory: 'server',
        example: '0',
      },
      {
        field: 'additionalInfo.statusSummary.temporary_unavailable',
        definition: 'Quantidade de recursos temporariamente indisponíveis',
        fillingRule: 'Número de recursos com status temporarily unavailable',
        roles: ['SERVER'],
        httpCodes: ['200'],
        mandatory: 'server',
        example: '1',
      },
      {
        field: 'additionalInfo.statusSummary.pending_authorisation',
        definition: 'Quantidade de recursos pendentes de autorização',
        fillingRule: 'Número de recursos com status pending authorisation',
        roles: ['SERVER'],
        httpCodes: ['200'],
        mandatory: 'server',
        example: '2',
      },
    ],
  },
]
